### ISSUE TITLE
Create Main Gameplay Loop

### ISSUE THREAD

**Issue by rzu-7** [rzu-7/pong2d#3]
The game should meet the following criteria
- [x] Is playable by one player
  - [x] Create controller script #1
  - [x] Create ball script #6
  - [x] Create game logic #7
  - [x] Create player input script #11
  - [x] Create main game scene #2
  - [ ] Create enemy script #12
  - [ ] Create ball speed bonus mechanic #10
- [x] There is a winner after 5 points #7
- [ ]  Opponent exhibits some form of behavior #12
- [x] Game resets after a winner is declared #7
