### ISSUE TITLE
Create "Releasable" Build

### ISSUE THREAD

**Issue by rzu-7** [rzu-7/pong2d#8]
The game should meet the following criteria:
## Has a main menu
- [ ] Start Game Button
  - Has a pop-up with the following options
    - [ ] Number of Players Selector
    - [ ] Difficulty Selector
    - [ ] Start Button
- [ ] Options Button
  - [ ] Sound Slider
  - [ ] Match Size Slider
- [ ] Quit Button
## Has Pause Menu
- [ ] Pause Label is Prominent
- [ ] Options Button
  - [ ] Continue Button
  - [ ] Sound Slider
- [ ] Restart Match Button
- [ ] Quit to Main Menu
- [ ] Quit to Desktop
## Has an End Game Menu
- [ ] Restart Match Button
- [ ] Quit to Main Menu
- [ ] Quit to Desktop
