### ISSUE TITLE
Finalize Release Build

### ISSUE THREAD

**Issue by rzu-7** [rzu-7/pong2d#9]
The build should meet the following requirements:
- [ ] opponent AI is fully functional
- [ ] Menus are stylized
- [ ] Game supports 2 players on the same device (PC only)
- [ ] Game has sound effects
- [ ] Game has difficulty options
  - [ ] Increasing ball speed
  - [ ] Reducing paddle height
- [ ] Game supports key remapping
